using System;
using System.Diagnostics;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace Crypto
{
    public class Program
    {


      
        private static void Main(string[] args)
        {
           // PerformansProfile("RSA-AES Hibrit Şifreleme | HybridTestFromMemoryAsync()", 1,
                //  () => HybridTestFromMemoryAsync().Wait());
            HybridTestFromMemoryAsync().Wait();
            Console.ReadLine();
        }


        private static async Task HybridTestFromMemoryAsync()
        {
            string publicKey = RsaAesHybrit.Instance.ToXmlString(false);
            string privateKey = RsaAesHybrit.Instance.ToXmlString(true);

            string metin = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6IjUwMDM4MyIsIkZ1bGxOYW1lIjoiUkFCxLBZQSBBWURJTiBHw5xMREVOIiwiUmVhbG1JZCI6IjEiLCJVc2VySWQiOiJkZWMxMTgwYy0zMzczLTQ3NDktOGZjNC03ODVjZDY0YWI5YTEiLCJSZWFsbU5hbWUiOiJQVFRHT1ZUUiIsIlBlcm1pc3Npb24iOlsiUGVybWlzc2lvbnMuTWVudXMuUmVhZCIsIlBlcm1pc3Npb25zLk1lbnVzLkFkZCIsIihDKVBlcm1pc3Npb25zLk1lbnVzLkVkaXQiLCIoQylQZXJtaXNzaW9ucy5NZW51cy5EZWxldGUiLCJQZXJtaXNzaW9ucy5NZW51cy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5Bbm5vdW5jZW1lbnRzLlJlYWQiLCJQZXJtaXNzaW9ucy5Bbm5vdW5jZW1lbnRzLkFkZCIsIihDKVBlcm1pc3Npb25zLkFubm91bmNlbWVudHMuRWRpdCIsIihDKVBlcm1pc3Npb25zLkFubm91bmNlbWVudHMuRGVsZXRlIiwiUGVybWlzc2lvbnMuQW5ub3VuY2VtZW50cy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5OZXdzLlJlYWQiLCJQZXJtaXNzaW9ucy5OZXdzLkFkZCIsIihDKVBlcm1pc3Npb25zLk5ld3MuRWRpdCIsIihDKVBlcm1pc3Npb25zLk5ld3MuRGVsZXRlIiwiUGVybWlzc2lvbnMuTmV3cy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5QYWdlcy5SZWFkIiwiUGVybWlzc2lvbnMuUGFnZXMuQWRkIiwiKEMpUGVybWlzc2lvbnMuUGFnZXMuRWRpdCIsIihDKVBlcm1pc3Npb25zLlBhZ2VzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLlBhZ2VzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlNsaWRlcnMuUmVhZCIsIlBlcm1pc3Npb25zLlNsaWRlcnMuQWRkIiwiKEMpUGVybWlzc2lvbnMuU2xpZGVycy5FZGl0IiwiKEMpUGVybWlzc2lvbnMuU2xpZGVycy5EZWxldGUiLCJQZXJtaXNzaW9ucy5TbGlkZXJzLk1hbmFnZSIsIlBlcm1pc3Npb25zLkFwcHJvdmFsUHJvY2Vzc2VzLlJlYWQiLCJQZXJtaXNzaW9ucy5BcHByb3ZhbFByb2Nlc3Nlcy5BZGQiLCJQZXJtaXNzaW9ucy5BcHByb3ZhbFByb2Nlc3Nlcy5FZGl0IiwiUGVybWlzc2lvbnMuQXBwcm92YWxQcm9jZXNzZXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuQXBwcm92YWxQcm9jZXNzZXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuU3VydmV5cy5SZWFkIiwiUGVybWlzc2lvbnMuU3VydmV5cy5BZGQiLCIoQylQZXJtaXNzaW9ucy5TdXJ2ZXlzLkVkaXQiLCIoQylQZXJtaXNzaW9ucy5TdXJ2ZXlzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLlN1cnZleXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuU3VydmV5UXVlc3Rpb25zLlJlYWQiLCJQZXJtaXNzaW9ucy5TdXJ2ZXlRdWVzdGlvbnMuQWRkIiwiKEMpUGVybWlzc2lvbnMuU3VydmV5UXVlc3Rpb25zLkVkaXQiLCIoQylQZXJtaXNzaW9ucy5TdXJ2ZXlRdWVzdGlvbnMuRGVsZXRlIiwiUGVybWlzc2lvbnMuU3VydmV5UXVlc3Rpb25zLk1hbmFnZSIsIlBlcm1pc3Npb25zLlNpdGVVc2VyUGVybWlzc2lvbi5SZWFkIiwiUGVybWlzc2lvbnMuU2l0ZVVzZXJQZXJtaXNzaW9uLkFkZCIsIlBlcm1pc3Npb25zLlNpdGVVc2VyUGVybWlzc2lvbi5FZGl0IiwiUGVybWlzc2lvbnMuU2l0ZVVzZXJQZXJtaXNzaW9uLkRlbGV0ZSIsIlBlcm1pc3Npb25zLlNpdGVVc2VyUGVybWlzc2lvbi5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5TdWJzY3JpYmVycy5SZWFkIiwiUGVybWlzc2lvbnMuU3Vic2NyaWJlcnMuQWRkIiwiKEMpUGVybWlzc2lvbnMuU3Vic2NyaWJlcnMuRWRpdCIsIihDKVBlcm1pc3Npb25zLlN1YnNjcmliZXJzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLlN1YnNjcmliZXJzLk1hbmFnZSIsIlBlcm1pc3Npb25zLkFwcHJvdmFsR3JvdXBVc2Vycy5SZWFkIiwiUGVybWlzc2lvbnMuQXBwcm92YWxHcm91cFVzZXJzLkFkZCIsIlBlcm1pc3Npb25zLkFwcHJvdmFsR3JvdXBVc2Vycy5FZGl0IiwiUGVybWlzc2lvbnMuQXBwcm92YWxHcm91cFVzZXJzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkFwcHJvdmFsR3JvdXBVc2Vycy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5GaWxlcy5SZWFkIiwiUGVybWlzc2lvbnMuRmlsZXMuQWRkIiwiUGVybWlzc2lvbnMuRmlsZXMuRWRpdCIsIlBlcm1pc3Npb25zLkZpbGVzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkZpbGVzLk1hbmFnZSIsIlBlcm1pc3Npb25zLkdlbmVyYWxGaWxlcy5SZWFkIiwiUGVybWlzc2lvbnMuR2VuZXJhbEZpbGVzLkFkZCIsIlBlcm1pc3Npb25zLkdlbmVyYWxGaWxlcy5FZGl0IiwiUGVybWlzc2lvbnMuR2VuZXJhbEZpbGVzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkdlbmVyYWxGaWxlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5Hcm91cHMuUmVhZCIsIlBlcm1pc3Npb25zLkdyb3Vwcy5BZGQiLCJQZXJtaXNzaW9ucy5Hcm91cHMuRWRpdCIsIlBlcm1pc3Npb25zLkdyb3Vwcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5Hcm91cHMuTWFuYWdlIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VzLlJlYWQiLCJQZXJtaXNzaW9ucy5MYW5ndWFnZXMuQWRkIiwiKEMpUGVybWlzc2lvbnMuTGFuZ3VhZ2VzLkVkaXQiLCIoQylQZXJtaXNzaW9ucy5MYW5ndWFnZXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VzLk1hbmFnZSIsIlBlcm1pc3Npb25zLkxhbmd1YWdlUmVzb3VyY2VzLlJlYWQiLCJQZXJtaXNzaW9ucy5MYW5ndWFnZVJlc291cmNlcy5BZGQiLCIoQylQZXJtaXNzaW9ucy5MYW5ndWFnZVJlc291cmNlcy5FZGl0IiwiKEMpUGVybWlzc2lvbnMuTGFuZ3VhZ2VSZXNvdXJjZXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VSZXNvdXJjZXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuU2hpcG1lbnRUcmFja2luZ3MuUmVhZCIsIlBlcm1pc3Npb25zLlNoaXBtZW50VHJhY2tpbmdzLkFkZCIsIlBlcm1pc3Npb25zLlNoaXBtZW50VHJhY2tpbmdzLkVkaXQiLCJQZXJtaXNzaW9ucy5TaGlwbWVudFRyYWNraW5ncy5EZWxldGUiLCJQZXJtaXNzaW9ucy5TaGlwbWVudFRyYWNraW5ncy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5Vc2Vycy5SZWFkIiwiUGVybWlzc2lvbnMuVXNlcnMuQWRkIiwiUGVybWlzc2lvbnMuVXNlcnMuRWRpdCIsIlBlcm1pc3Npb25zLlVzZXJzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLlVzZXJzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlNsaWRlckRldGFpbHMuUmVhZCIsIlBlcm1pc3Npb25zLlNsaWRlckRldGFpbHMuQWRkIiwiKEMpUGVybWlzc2lvbnMuU2xpZGVyRGV0YWlscy5FZGl0IiwiKEMpUGVybWlzc2lvbnMuU2xpZGVyRGV0YWlscy5EZWxldGUiLCJQZXJtaXNzaW9ucy5TbGlkZXJEZXRhaWxzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlJvbGVzLlZpZXciLCJQZXJtaXNzaW9ucy5Sb2xlcy5BZGQiLCJQZXJtaXNzaW9ucy5Sb2xlcy5FZGl0IiwiUGVybWlzc2lvbnMuUm9sZXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuUm9sZXMuTWFuYWdlQ2xhaW1zIiwiUGVybWlzc2lvbnMuQXBwcm92ZXJNYW5hZ2VtZW50LlZpZXciLCJQZXJtaXNzaW9ucy5BcHByb3Zlck1hbmFnZW1lbnQuQWRkIiwiUGVybWlzc2lvbnMuQXBwcm92ZXJNYW5hZ2VtZW50LkVkaXQiLCJQZXJtaXNzaW9ucy5BcHByb3Zlck1hbmFnZW1lbnQuRGVsZXRlIiwiUGVybWlzc2lvbnMuQXBwcm92ZXJNYW5hZ2VtZW50Lk1hbmFnZSIsIlBlcm1pc3Npb25zLkFwcHJvdmVyTWFuYWdlbWVudC5SZWFkIiwiUGVybWlzc2lvbnMuU2l0ZXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuU2l0ZXMuUmVhZCIsIlBlcm1pc3Npb25zLk1lbnVzLlJlYWQiLCJQZXJtaXNzaW9ucy5NZW51cy5BZGQiLCJQZXJtaXNzaW9ucy5NZW51cy5FZGl0IiwiUGVybWlzc2lvbnMuTWVudXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuTWVudXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuQW5ub3VuY2VtZW50cy5SZWFkIiwiUGVybWlzc2lvbnMuQW5ub3VuY2VtZW50cy5BZGQiLCJQZXJtaXNzaW9ucy5Bbm5vdW5jZW1lbnRzLkVkaXQiLCJQZXJtaXNzaW9ucy5Bbm5vdW5jZW1lbnRzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkFubm91bmNlbWVudHMuTWFuYWdlIiwiUGVybWlzc2lvbnMuTmV3cy5SZWFkIiwiUGVybWlzc2lvbnMuTmV3cy5BZGQiLCJQZXJtaXNzaW9ucy5OZXdzLkVkaXQiLCJQZXJtaXNzaW9ucy5OZXdzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLk5ld3MuTWFuYWdlIiwiUGVybWlzc2lvbnMuUGFnZXMuUmVhZCIsIlBlcm1pc3Npb25zLlBhZ2VzLkFkZCIsIlBlcm1pc3Npb25zLlBhZ2VzLkVkaXQiLCJQZXJtaXNzaW9ucy5QYWdlcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5QYWdlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5TbGlkZXJzLlJlYWQiLCJQZXJtaXNzaW9ucy5TbGlkZXJzLkFkZCIsIlBlcm1pc3Npb25zLlNsaWRlcnMuRWRpdCIsIlBlcm1pc3Npb25zLlNsaWRlcnMuRGVsZXRlIiwiUGVybWlzc2lvbnMuU2xpZGVycy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5BcHByb3ZhbFByb2Nlc3Nlcy5SZWFkIiwiUGVybWlzc2lvbnMuQXBwcm92YWxQcm9jZXNzZXMuQWRkIiwiUGVybWlzc2lvbnMuQXBwcm92YWxQcm9jZXNzZXMuRWRpdCIsIlBlcm1pc3Npb25zLkFwcHJvdmFsUHJvY2Vzc2VzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkFwcHJvdmFsUHJvY2Vzc2VzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlN1cnZleXMuUmVhZCIsIlBlcm1pc3Npb25zLlN1cnZleXMuQWRkIiwiUGVybWlzc2lvbnMuU3VydmV5cy5FZGl0IiwiUGVybWlzc2lvbnMuU3VydmV5cy5EZWxldGUiLCJQZXJtaXNzaW9ucy5TdXJ2ZXlzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlN1cnZleVF1ZXN0aW9ucy5SZWFkIiwiUGVybWlzc2lvbnMuU3VydmV5UXVlc3Rpb25zLkFkZCIsIlBlcm1pc3Npb25zLlN1cnZleVF1ZXN0aW9ucy5FZGl0IiwiUGVybWlzc2lvbnMuU3VydmV5UXVlc3Rpb25zLkRlbGV0ZSIsIlBlcm1pc3Npb25zLlN1cnZleVF1ZXN0aW9ucy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5TaXRlVXNlclBlcm1pc3Npb24uUmVhZCIsIlBlcm1pc3Npb25zLlNpdGVVc2VyUGVybWlzc2lvbi5BZGQiLCJQZXJtaXNzaW9ucy5TaXRlVXNlclBlcm1pc3Npb24uRWRpdCIsIlBlcm1pc3Npb25zLlNpdGVVc2VyUGVybWlzc2lvbi5EZWxldGUiLCJQZXJtaXNzaW9ucy5TaXRlVXNlclBlcm1pc3Npb24uTWFuYWdlIiwiUGVybWlzc2lvbnMuU3Vic2NyaWJlcnMuUmVhZCIsIlBlcm1pc3Npb25zLlN1YnNjcmliZXJzLkFkZCIsIlBlcm1pc3Npb25zLlN1YnNjcmliZXJzLkVkaXQiLCJQZXJtaXNzaW9ucy5TdWJzY3JpYmVycy5EZWxldGUiLCJQZXJtaXNzaW9ucy5TdWJzY3JpYmVycy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5BcHByb3ZhbEdyb3VwVXNlcnMuUmVhZCIsIlBlcm1pc3Npb25zLkFwcHJvdmFsR3JvdXBVc2Vycy5BZGQiLCJQZXJtaXNzaW9ucy5BcHByb3ZhbEdyb3VwVXNlcnMuRWRpdCIsIlBlcm1pc3Npb25zLkFwcHJvdmFsR3JvdXBVc2Vycy5EZWxldGUiLCJQZXJtaXNzaW9ucy5BcHByb3ZhbEdyb3VwVXNlcnMuTWFuYWdlIiwiUGVybWlzc2lvbnMuRmlsZXMuUmVhZCIsIlBlcm1pc3Npb25zLkZpbGVzLkFkZCIsIlBlcm1pc3Npb25zLkZpbGVzLkVkaXQiLCJQZXJtaXNzaW9ucy5GaWxlcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5GaWxlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5HZW5lcmFsRmlsZXMuUmVhZCIsIlBlcm1pc3Npb25zLkdlbmVyYWxGaWxlcy5BZGQiLCJQZXJtaXNzaW9ucy5HZW5lcmFsRmlsZXMuRWRpdCIsIlBlcm1pc3Npb25zLkdlbmVyYWxGaWxlcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5HZW5lcmFsRmlsZXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuR3JvdXBzLlJlYWQiLCJQZXJtaXNzaW9ucy5Hcm91cHMuQWRkIiwiUGVybWlzc2lvbnMuR3JvdXBzLkVkaXQiLCJQZXJtaXNzaW9ucy5Hcm91cHMuRGVsZXRlIiwiUGVybWlzc2lvbnMuR3JvdXBzLk1hbmFnZSIsIlBlcm1pc3Npb25zLkxhbmd1YWdlcy5SZWFkIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VzLkFkZCIsIlBlcm1pc3Npb25zLkxhbmd1YWdlcy5FZGl0IiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkxhbmd1YWdlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5MYW5ndWFnZVJlc291cmNlcy5SZWFkIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VSZXNvdXJjZXMuQWRkIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VSZXNvdXJjZXMuRWRpdCIsIlBlcm1pc3Npb25zLkxhbmd1YWdlUmVzb3VyY2VzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkxhbmd1YWdlUmVzb3VyY2VzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlNoaXBtZW50VHJhY2tpbmdzLlJlYWQiLCJQZXJtaXNzaW9ucy5TaGlwbWVudFRyYWNraW5ncy5BZGQiLCJQZXJtaXNzaW9ucy5TaGlwbWVudFRyYWNraW5ncy5FZGl0IiwiUGVybWlzc2lvbnMuU2hpcG1lbnRUcmFja2luZ3MuRGVsZXRlIiwiUGVybWlzc2lvbnMuU2hpcG1lbnRUcmFja2luZ3MuTWFuYWdlIiwiUGVybWlzc2lvbnMuU2l0ZXMuUmVhZCIsIlBlcm1pc3Npb25zLlNpdGVzLkFkZCIsIlBlcm1pc3Npb25zLlNpdGVzLkVkaXQiLCJQZXJtaXNzaW9ucy5TaXRlcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5TaXRlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5Vc2Vycy5SZWFkIiwiUGVybWlzc2lvbnMuVXNlcnMuQWRkIiwiUGVybWlzc2lvbnMuVXNlcnMuRWRpdCIsIlBlcm1pc3Npb25zLlVzZXJzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLlVzZXJzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlNsaWRlckRldGFpbHMuUmVhZCIsIlBlcm1pc3Npb25zLlNsaWRlckRldGFpbHMuQWRkIiwiUGVybWlzc2lvbnMuU2xpZGVyRGV0YWlscy5FZGl0IiwiUGVybWlzc2lvbnMuU2xpZGVyRGV0YWlscy5EZWxldGUiLCJQZXJtaXNzaW9ucy5TbGlkZXJEZXRhaWxzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlJvbGVzLlJlYWQiLCJQZXJtaXNzaW9ucy5Sb2xlcy5BZGQiLCJQZXJtaXNzaW9ucy5Sb2xlcy5FZGl0IiwiUGVybWlzc2lvbnMuUm9sZXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuUm9sZXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuR2FsbGVyaWVzLlJlYWQiLCJQZXJtaXNzaW9ucy5HYWxsZXJpZXMuQWRkIiwiUGVybWlzc2lvbnMuR2FsbGVyaWVzLkVkaXQiLCJQZXJtaXNzaW9ucy5HYWxsZXJpZXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuR2FsbGVyaWVzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlB1Ymxpc2hlcy5SZWFkIiwiUGVybWlzc2lvbnMuUHVibGlzaGVzLkFkZCIsIlBlcm1pc3Npb25zLlB1Ymxpc2hlcy5FZGl0IiwiUGVybWlzc2lvbnMuUHVibGlzaGVzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLlB1Ymxpc2hlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5Sb2xlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5Sb2xlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5Sb2xlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5Sb2xlcy5SZWFkIiwiUGVybWlzc2lvbnMuQW5ub3VuY2VtZW50cy5SZWFkIiwiUGVybWlzc2lvbnMuQW5ub3VuY2VtZW50cy5BZGQiLCJQZXJtaXNzaW9ucy5Bbm5vdW5jZW1lbnRzLkVkaXQiLCJQZXJtaXNzaW9ucy5Bbm5vdW5jZW1lbnRzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkFubm91bmNlbWVudHMuTWFuYWdlIiwiUGVybWlzc2lvbnMuTmV3cy5SZWFkIiwiUGVybWlzc2lvbnMuTmV3cy5BZGQiLCJQZXJtaXNzaW9ucy5OZXdzLkVkaXQiLCJQZXJtaXNzaW9ucy5OZXdzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLk5ld3MuTWFuYWdlIiwiUGVybWlzc2lvbnMuUGFnZXMuUmVhZCIsIlBlcm1pc3Npb25zLlBhZ2VzLkFkZCIsIlBlcm1pc3Npb25zLlBhZ2VzLkVkaXQiLCJQZXJtaXNzaW9ucy5QYWdlcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5QYWdlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5TbGlkZXJzLlJlYWQiLCJQZXJtaXNzaW9ucy5TbGlkZXJzLkFkZCIsIlBlcm1pc3Npb25zLlNsaWRlcnMuRWRpdCIsIlBlcm1pc3Npb25zLlNsaWRlcnMuRGVsZXRlIiwiUGVybWlzc2lvbnMuU2xpZGVycy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5GaWxlcy5SZWFkIiwiUGVybWlzc2lvbnMuRmlsZXMuQWRkIiwiUGVybWlzc2lvbnMuRmlsZXMuRWRpdCIsIlBlcm1pc3Npb25zLkZpbGVzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkZpbGVzLk1hbmFnZSIsIlBlcm1pc3Npb25zLkdlbmVyYWxGaWxlcy5SZWFkIiwiUGVybWlzc2lvbnMuR2VuZXJhbEZpbGVzLkFkZCIsIlBlcm1pc3Npb25zLkdlbmVyYWxGaWxlcy5FZGl0IiwiUGVybWlzc2lvbnMuR2VuZXJhbEZpbGVzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkdlbmVyYWxGaWxlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5MYW5ndWFnZXMuUmVhZCIsIlBlcm1pc3Npb25zLkxhbmd1YWdlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5MYW5ndWFnZVJlc291cmNlcy5SZWFkIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VSZXNvdXJjZXMuQWRkIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VSZXNvdXJjZXMuRWRpdCIsIlBlcm1pc3Npb25zLkxhbmd1YWdlUmVzb3VyY2VzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkxhbmd1YWdlUmVzb3VyY2VzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlNsaWRlckRldGFpbHMuUmVhZCIsIlBlcm1pc3Npb25zLlNsaWRlckRldGFpbHMuQWRkIiwiUGVybWlzc2lvbnMuU2xpZGVyRGV0YWlscy5FZGl0IiwiUGVybWlzc2lvbnMuU2xpZGVyRGV0YWlscy5EZWxldGUiLCJQZXJtaXNzaW9ucy5TbGlkZXJEZXRhaWxzLk1hbmFnZSIsIlBlcm1pc3Npb25zLkFubm91bmNlbWVudHMuTWFuYWdlIiwiUGVybWlzc2lvbnMuRmlsZXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuR2FsbGVyaWVzLk1hbmFnZSIsIlBlcm1pc3Npb25zLkdlbmVyYWxGaWxlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5Hcm91cHMuTWFuYWdlIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VSZXNvdXJjZXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VzLk1hbmFnZSIsIlBlcm1pc3Npb25zLk1lbnVzLk1hbmFnZSIsIlBlcm1pc3Npb25zLk5ld3MuTWFuYWdlIiwiUGVybWlzc2lvbnMuUGFnZXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuUHVibGlzaGVzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlNsaWRlckRldGFpbHMuTWFuYWdlIiwiUGVybWlzc2lvbnMuU2xpZGVycy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5TdXJ2ZXlzLk1hbmFnZSIsIlBlcm1pc3Npb25zLk1lbnVzLlJlYWQiLCJQZXJtaXNzaW9ucy5NZW51cy5BZGQiLCJQZXJtaXNzaW9ucy5NZW51cy5FZGl0IiwiUGVybWlzc2lvbnMuTWVudXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuR2FsbGVyaWVzLlJlYWQiLCJQZXJtaXNzaW9ucy5HYWxsZXJpZXMuQWRkIiwiUGVybWlzc2lvbnMuR2FsbGVyaWVzLkVkaXQiLCJQZXJtaXNzaW9ucy5HYWxsZXJpZXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuUHVibGlzaGVzLlJlYWQiLCJQZXJtaXNzaW9ucy5QdWJsaXNoZXMuQWRkIiwiUGVybWlzc2lvbnMuUHVibGlzaGVzLkVkaXQiLCJQZXJtaXNzaW9ucy5QdWJsaXNoZXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuTWVudXMuUmVhZCIsIlBlcm1pc3Npb25zLk1lbnVzLkFkZCIsIlBlcm1pc3Npb25zLk1lbnVzLkVkaXQiLCJQZXJtaXNzaW9ucy5NZW51cy5EZWxldGUiLCJQZXJtaXNzaW9ucy5HYWxsZXJpZXMuUmVhZCIsIlBlcm1pc3Npb25zLkdhbGxlcmllcy5BZGQiLCJQZXJtaXNzaW9ucy5HYWxsZXJpZXMuRWRpdCIsIlBlcm1pc3Npb25zLkdhbGxlcmllcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5QdWJsaXNoZXMuUmVhZCIsIlBlcm1pc3Npb25zLlB1Ymxpc2hlcy5BZGQiLCJQZXJtaXNzaW9ucy5QdWJsaXNoZXMuRWRpdCIsIlBlcm1pc3Npb25zLlB1Ymxpc2hlcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5TdXJ2ZXlzLlJlYWQiLCJQZXJtaXNzaW9ucy5TdXJ2ZXlzLkFkZCIsIlBlcm1pc3Npb25zLlN1cnZleXMuRWRpdCIsIlBlcm1pc3Npb25zLlN1cnZleXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuQXBwcm92YWxQcm9jZXNzZXMuUmVhZCIsIlBlcm1pc3Npb25zLlN1cnZleVF1ZXN0aW9ucy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5TdXJ2ZXlRdWVzdGlvbnMuUmVhZCIsIlBlcm1pc3Npb25zLlN1cnZleVF1ZXN0aW9ucy5BZGQiLCJQZXJtaXNzaW9ucy5TdXJ2ZXlRdWVzdGlvbnMuRWRpdCIsIlBlcm1pc3Npb25zLlN1cnZleVF1ZXN0aW9ucy5EZWxldGUiLCJQZXJtaXNzaW9ucy5BcHByb3ZhbFByb2Nlc3Nlcy5SZWFkIiwiUGVybWlzc2lvbnMuQXBwcm92YWxQcm9jZXNzZXMuQWRkIiwiUGVybWlzc2lvbnMuQXBwcm92YWxQcm9jZXNzZXMuRWRpdCIsIlBlcm1pc3Npb25zLkFwcHJvdmFsUHJvY2Vzc2VzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkFwcHJvdmFsUHJvY2Vzc2VzLk1hbmFnZSIsIihDKVBlcm1pc3Npb25zLkFwcHJvdmFsR3JvdXBVc2Vycy5SZWFkIiwiKEMpUGVybWlzc2lvbnMuQXBwcm92YWxHcm91cFVzZXJzLkFkZCIsIihDKVBlcm1pc3Npb25zLkFwcHJvdmFsR3JvdXBVc2Vycy5FZGl0IiwiKEMpUGVybWlzc2lvbnMuQXBwcm92YWxHcm91cFVzZXJzLkRlbGV0ZSIsIihDKVBlcm1pc3Npb25zLkFwcHJvdmFsR3JvdXBVc2Vycy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5HZW5lcmFsRmlsZXMuUmVhZCIsIlBlcm1pc3Npb25zLkdlbmVyYWxGaWxlcy5BZGQiLCJQZXJtaXNzaW9ucy5HZW5lcmFsRmlsZXMuRWRpdCIsIlBlcm1pc3Npb25zLkdlbmVyYWxGaWxlcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5HZW5lcmFsRmlsZXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VzLlJlYWQiLCJQZXJtaXNzaW9ucy5MYW5ndWFnZXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VSZXNvdXJjZXMuUmVhZCIsIlBlcm1pc3Npb25zLkxhbmd1YWdlUmVzb3VyY2VzLkFkZCIsIihDKVBlcm1pc3Npb25zLkxhbmd1YWdlUmVzb3VyY2VzLkVkaXQiLCIoQylQZXJtaXNzaW9ucy5MYW5ndWFnZVJlc291cmNlcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5MYW5ndWFnZVJlc291cmNlcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5Bbm5vdW5jZW1lbnRzLk1hbmFnZSIsIlBlcm1pc3Npb25zLkFwcHJvdmFsUHJvY2Vzc2VzLk1hbmFnZSIsIlBlcm1pc3Npb25zLkdhbGxlcmllcy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5Hcm91cHMuTWFuYWdlIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VSZXNvdXJjZXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuTGFuZ3VhZ2VzLk1hbmFnZSIsIlBlcm1pc3Npb25zLk1lbnVzLk1hbmFnZSIsIlBlcm1pc3Npb25zLk5ld3MuTWFuYWdlIiwiUGVybWlzc2lvbnMuUGFnZXMuTWFuYWdlIiwiUGVybWlzc2lvbnMuUHVibGlzaGVzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlNoaXBtZW50VHJhY2tpbmdzLk1hbmFnZSIsIlBlcm1pc3Npb25zLlNsaWRlckRldGFpbHMuTWFuYWdlIiwiUGVybWlzc2lvbnMuU2xpZGVycy5NYW5hZ2UiLCJQZXJtaXNzaW9ucy5TdXJ2ZXlzLk1hbmFnZSIsIlBlcm1pc3Npb25zLk1lbnVzLlJlYWQiLCJQZXJtaXNzaW9ucy5HYWxsZXJpZXMuUmVhZCIsIlBlcm1pc3Npb25zLlB1Ymxpc2hlcy5SZWFkIiwiUGVybWlzc2lvbnMuU3VydmV5cy5SZWFkIiwiUGVybWlzc2lvbnMuQW5ub3VuY2VtZW50cy5SZWFkIiwiUGVybWlzc2lvbnMuUGFnZXMuUmVhZCIsIlBlcm1pc3Npb25zLk5ld3MuUmVhZCIsIlBlcm1pc3Npb25zLlNsaWRlcnMuUmVhZCIsIlBlcm1pc3Npb25zLlNsaWRlckRldGFpbHMuUmVhZCJdLCJSb2xlTmFtZXMiOlsiQWRtaW4iLCJTdXBlckFkbWluIiwiRWRpdG9yIiwiT25heWxheWljaSIsIk1pc2FmaXIiXSwiZXhwIjoxNjkxMDk2NTE5LCJpc3MiOiJQVFRXZWJTaXRlX0FkbWluQXBpIn0.xvc2QcXpakEkdyNGZ4XVY5TpElKKwHY4jQy8TQNeCEk";

            byte[] orijinal = Encoding.UTF8.GetBytes(metin);
            byte[] sifrele = await RsaAesHybrit.Instance.EncryptAsync(orijinal);
            byte[] cozuldu = await RsaAesHybrit.Instance.DecryptAsync(sifrele);
            string cozumMetin = Encoding.UTF8.GetString(cozuldu);

            Console.WriteLine("Public Key\t: {0}\r\n", publicKey);
            Console.WriteLine("Private Key\t:{0}\r\n", privateKey);

            Console.WriteLine("Orijinal\t: {0}\r\n", metin);
            Console.WriteLine("Sifrelenmiş\t: {0}\r\n", Convert.ToBase64String(sifrele));
            Console.WriteLine("Çözüm\t\t: {0}\r\n", cozumMetin);
            LogAppend(ConsoleColor.White, "Hash\t\t: ");
            if (BitConverter.ToString(MD5.Create().ComputeHash(orijinal)) == BitConverter.ToString(MD5.Create().ComputeHash(cozuldu)))
                LogLine(ConsoleColor.Green, "Doğrulandı.");
            else
                LogLine(ConsoleColor.Red, "Yanlış.");
        }










        #region " Helper Methods "
        public static string MD5Hash(string fileName)
        {
            using (var stream = new BufferedStream(File.OpenRead(fileName), 32768))
            {
                MD5 md5 = new MD5CryptoServiceProvider();
                byte[] hash = md5.ComputeHash(stream);
                StringBuilder stringBuilder = new StringBuilder();
                foreach (byte b in hash)
                    stringBuilder.AppendFormat("{0:x2}", b);
                return stringBuilder.ToString();
            }
        }
        public static void PerformansProfile(string description, int iterations, Action method)
        {
            LogLine(ConsoleColor.Yellow, new string('-', 67));
            LogLine(ConsoleColor.Blue, string.Format("[Profil: {0}]", description));

            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();

            var watch = Stopwatch.StartNew();
            for (int i = 0; i < iterations; i++)
                method();
            watch.Stop();
            LogLine(ConsoleColor.Green, string.Format("Geçen Zaman\t: {0:00}:{1:00}:{2:00}.{3:00}", watch.Elapsed.TotalHours, watch.Elapsed.TotalMinutes, watch.Elapsed.TotalSeconds, watch.Elapsed.TotalMilliseconds));
            LogLine(ConsoleColor.Yellow, new string('-', 67));
            Console.WriteLine(Environment.NewLine);
        }
        public static void LogLine(ConsoleColor color, string format, params object[] arg)
        {
            Console.BackgroundColor = ConsoleColor.Black;
            Console.ForegroundColor = color;
            Console.WriteLine(format, arg);
            Console.ForegroundColor = ConsoleColor.White;
        }
        public static void LogAppend(ConsoleColor color, string format, params object[] arg)
        {
            Console.ForegroundColor = color;
            Console.Write(format, arg);
            Console.ForegroundColor = ConsoleColor.White;
        }
        #endregion
    }
}